apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Changed from LoadBalancer to NodePort for Minikube
  selector:
    app: nginx  # Note: No version selector to include both base and canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Added nodePort for external access (must be between 30000-32767)
